/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testcontainers1;

import org.apache.hc.client5.http.ClientProtocolException;
import org.apache.hc.client5.http.classic.methods.HttpGet;
import org.apache.hc.client5.http.impl.classic.CloseableHttpClient;
import org.apache.hc.client5.http.impl.classic.HttpClients;
import org.apache.hc.core5.http.ClassicHttpResponse;
import org.apache.hc.core5.http.HttpEntity;
import org.apache.hc.core5.http.HttpStatus;
import org.apache.hc.core5.http.ParseException;
import org.apache.hc.core5.http.io.entity.EntityUtils;
import org.assertj.core.api.Assertions;
import org.junit.Before;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.slf4j.LoggerFactory;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.containers.MockServerContainer;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.containers.output.Slf4jLogConsumer;
import org.testcontainers.containers.wait.strategy.Wait;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import javax.json.Json;
import javax.json.JsonArray;
import javax.json.JsonObject;
import javax.json.bind.JsonbBuilder;
import java.io.IOException;
import java.io.StringReader;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

@Testcontainers
class AppTest {

    public static GenericContainer<?> postgreSQLContainer = new PostgreSQLContainer<>()
            .withDatabaseName("pg")
            .withUsername("alex")
            .withPassword("alex")
            .withNetworkAliases("postgres");


    @Container
    public static GenericContainer<?> payara = new GenericContainer<>(
            new testcontainers1.ImageFromDockerfile("bla").withBaseDirectory(Paths.get("Deployment")).withDockerfile(Paths.get("Deployment/Dockerfile")))
            .withNetworkAliases("payara")
            .withExposedPorts(8080)
            .waitingFor(Wait.forHttp("/myservice/app/people/all"));


    public MockServerContainer mockServer = new MockServerContainer().withNetworkAliases("mockserver");

    public static GenericContainer<?> openid = new GenericContainer<>("quay.io/appvia/mock-oidc-user-server:v0.0.2")
            .withEnv("PORT", "9090")
            .withEnv("CLIENT_ID", "my-client")
            .withEnv("CLIENT_SECRET", "my-secret")
            .withEnv("CLIENT_REDIRECT_URI", "http://applicationserver:8080/myservice/cb")
            .withEnv("CLIENT_LOGOUT_REDIRECT_URI", "http://applicationserver:8080/myservice/cb")
            .withExposedPorts(9090)
            .withNetworkAliases("openidmock");


    @BeforeAll
    public static void setup() {
        Slf4jLogConsumer logConsumer = new Slf4jLogConsumer(LoggerFactory.getLogger("Payara-Log:"));
        payara.followOutput(logConsumer);
    }

    @Test
    public void testSimpleGet() throws IOException {
        assertTrue(payara.isRunning());
        try (final CloseableHttpClient httpclient = HttpClients.createDefault()) {
            final String responseBody = httpclient.execute(new HttpGet("http://" + payara.getHost() + ":" + payara.getMappedPort(8080) + "/myservice/app/people/all"), AppTest::handleResponse);
            List<Person> persons = JsonbBuilder.create().fromJson(responseBody,new ArrayList<Person>(){}.getClass().getGenericSuperclass());
            Assertions.assertThat(persons)
                    .hasSize(2)
                    .anySatisfy(it -> Assertions.assertThat(it.age).isEqualTo(25))
                    .anySatisfy(it -> Assertions.assertThat(it.age).isEqualTo(26));
        }
    }

    private static String handleResponse(ClassicHttpResponse response) throws IOException {
        final int status = response.getCode();
        if (status >= HttpStatus.SC_SUCCESS && status < HttpStatus.SC_REDIRECTION) {
            final HttpEntity entity = response.getEntity();
            try {
                return entity != null ? EntityUtils.toString(entity) : null;
            } catch (final ParseException ex) {
                throw new ClientProtocolException(ex);
            }
        } else {
            throw new ClientProtocolException("Unexpected response status: " + status);
        }
    }
}
